### PR TITLE
automatic type identification for issue #5

### PR DESCRIPTION
**Pull request by 1beb**
- update documentation for optional factor creation
- adding functionality for automatic type identification in `responses$answers`

### CODE REVIEW

**Comment by csgillespie** [comment]
Thanks for the PR. Thinking about converting a bit more do you think anyone would ever set `as.is =FALSE`. In Questionnaire, factors are rarely needed. 

Basically, I think we should just  remove the as.is argument and run type.convert with as.is  =TRUE

---
Also, would you update the NEWS. Ta.

**Comment by 1beb** [comment]
I'm just thinking about the people that will use base summary. If we leave
it as character they are losing information.

On Apr 22, 2017 1:57 PM, "Colin Gillespie" <notifications@github.com> wrote:

Thanks for the PR. Thinking about converting a bit more do you think anyone
would ever set as.is =FALSE. In Questionnaire, factors are rarely needed.

Basically, I think we should just remove the as.is argument and run
type.convert with as.is =TRUE
------------------------------

Also, would you update the NEWS. Ta.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/csgillespie/rtypeform/pull/6#issuecomment-296394109>,
or mute the thread

**Comment by csgillespie** [comment]
Sorry, I don't quite follow. I'm proposing that we should automatically apply `type.convert()` to all columns. Since this is what read.table does, it should be OK. 

Am I missing something?

**Comment by 1beb** [comment]
Yes. If we use as.is = TRUE, by default, columns that ought to be factors
will be character. When you call summary on the resulting data, you get
just a count of a character column, but a factor is much more useful.

**Comment by csgillespie** [comment]
Ahh, it's clicked. 

In that case, would it make sense to have the argument as `stringsAsFactors = default.stringsAsFactors()`

Looking at the `read.table` definition, the default value of `as.is` is `!stringsAsFactors`, so using `stringsAsFactors` would make it obvious what it does (whereas `as.is`, doesn't).

**Comment by 1beb** [comment]
I suppose it's just naming. I'll update the PR accordingly.

Brandon Erik Bertelsen
647 287 1009
brandon@bertelsen.ca
Linkedin <http://www.linkedin.com/in/bbertelsen>

**Comment by 1beb** [comment]
PS: I can't use my API for testthat tests, so not sure if you have a plan for this with Travis, that seems to be the point of failure.

**Comment by csgillespie** [comment]
It seems that travis doesn't allow pull requests to access encrypted variables (i.e. typeform id).

**Comment by 1beb** [comment]
Sucks, but I suppose it makes sense. Someone could technically write something to expose the variable(s) at the console pretty easily if it did.

**Pull request merged**
